version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - neo_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  neo4j:
    image: neo4j:5.17-enterprise
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: ${NEO4J_ACCEPT_LICENSE_AGREEMENT}
      NEO4J_PLUGINS: '["apoc","graph-data-science","bloom"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*,bloom.*
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
    volumes:
      - neo4j_data:/data
      - ./import_raw:/var/lib/neo4j/import
    networks:
      - neo_net

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    user: root
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_started
    environment:
      AIRFLOW_UID: ${AIRFLOW_UID}
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW_LOAD_EXAMPLES}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}

      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_ADMIN_USER}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
      _AIRFLOW_WWW_USER_FIRSTNAME: ${AIRFLOW_ADMIN_FIRSTNAME}
      _AIRFLOW_WWW_USER_LASTNAME: ${AIRFLOW_ADMIN_LASTNAME}
      _AIRFLOW_WWW_USER_EMAIL: ${AIRFLOW_ADMIN_EMAIL}

      PYTHONPATH: /opt/airflow:/opt/airflow/scripts

      # ðŸ”¹ VariÃ¡veis usadas pelo script Python
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      SOURCE_DIR: ${SOURCE_DIR}
      NEO4J_IMPORT_DIR: ${NEO4J_IMPORT_DIR}
      MAX_LINES_PER_FILE: ${MAX_LINES_PER_FILE}

    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./import_raw:/opt/airflow/import_raw
      - ./bases_neo4j:/opt/bases_neo4j
      - airflow_logs:/opt/airflow/logs
    entrypoint: /entrypoint.sh
    networks:
      - neo_net

volumes:
  neo4j_data:
  postgres_data:
  airflow_logs:

networks:
  neo_net:
    driver: bridge
